# Generated by Django 5.0.7 on 2024-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('done', 'Done')], default='todo', max_length=4)),
            ],
        ),
    ]
